@BASEURL = http://localhost:8080
@V1 = v1

# @name GetOpening
GET {{BASEURL}}/api/{{V1}}/opening
Host: localhost:8080
Content-Type: application/json

###
# @name CreateOpening
POST {{BASEURL}}/api/{{V1}}/opening
Host: localhost:8080
Content-Type: application/json

{
  "role": "Senior da vida e do universo",
  "company": "Ultrasoft",
  "location": "Mossoró",
  "remote": true,
  "link": "https//vagapica.com",
  "salary": 52000
}

###
# @name DeleteOpening
DELETE {{BASEURL}}/api/{{V1}}/opening
Host: localhost:8080
Content-Type: application/json

###
# @name UpdateOpening
PUT {{BASEURL}}/api/{{V1}}/opening
Host: localhost:8080
Content-Type: application/json

{

}

###
# @name ListOpenings
GET {{BASEURL}}/api/{{V1}}/openings
Host: localhost:8080
Content-Type: application/json